# Generated by Django 5.0.6 on 2024-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
